# Sklearn Course
Program code of the sklearn course by freeCodeCamp.org: https://www.youtube.com/watch?v=pqNCD_5r0IU&list=WL&index=3

## Classification


### KNN - k-nearest-neighors algorithm
Seperates datapoints in regions -> number of axis equal to the number of features

In [12]:
# Import Libs
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [18]:
# Import data
data = pd.read_csv("car.data")
data.head()

buying  maint doors persons lug_boots safety  class
0  vhigh  vhigh     2       2     small    low  unacc
1  vhigh  vhigh     2       2     small    med  unacc
2  vhigh  vhigh     2       2     small   high  unacc
3  vhigh  vhigh     2       2       med    low  unacc
4  vhigh  vhigh     2       2       med    med  unacc

In [50]:
# split data
labels = data.columns
X = data[labels[0:-1]].values # convert to numpy array
y = data[["class"]]

In [51]:
# converting X using labelencoder from strings to integer
encoder = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = encoder.fit_transform(X[:, i])
print(X)


# converting y from strings to integer without using labelencoder  
label_mapping = {
    "unacc": 0, 
    "acc": 1, 
    "good": 2, 
    "vgood": 3
}
y["class"] = y["class"].map(label_mapping)
y = np.array(y) # here not using values because every element is in its own subarray => later useful


[[3 3 0 0 2 1]
 [3 3 0 0 2 2]
 [3 3 0 0 2 0]
 ...
 [1 1 3 2 0 1]
 [1 1 3 2 0 2]
 [1 1 3 2 0 0]]


C:\Users\s8gre\AppData\Local\Temp\ipykernel_2604\2279367143.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["class"] = y["class"].map(label_mapping)


In [52]:
# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [53]:
# weight parameter: 
#   uniform: every datapoint is equal
#   distance: closer datapoints are more important
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights="uniform")
# training the model
knn.fit(X_train, y_train)

c:\Users\s8gre\anaconda3\envs\ai\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [54]:
# test the model
prediction = knn.predict(X_test)
# get accuracy of the model
accuracy = metrics.accuracy_score(y_test, prediction)
print("accuracy: ", accuracy)

accuracy:  0.7254335260115607


### SVM - Support Vector Machine


## Regression